spring:
  data:
    mongodb:
      uri: mongodb://<DB_USERNAME>:<DB_PASSOWRD>@<HOST>:<PORT>/feeder?authSource=admin&ssl=false
  main:
    banner-mode: off

server:
  port: 9998
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: <KEYSTORE_PASSWORD>
    key-store: classpath:<PATH_TO_KEYSTORE>
    key-alias: <KEY_ALIAS>