spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/feeder?authSource=admin&ssl=false

server:
  port: 9998
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: localhostPassword
    key-store: classpath:keystore/identity.p12
    key-alias: mykey